language: rust

matrix:

  allow_failures:
    - rust: nightly

  fast_finish: true

  include:

  - rust: stable
    after_success:
    - cargo bench

  - rust: beta

  - rust: nightly
    before_script:
    - rustup component add rustfmt
    after_success:
    - cargo fmt --all -- --check
