language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
after_success:
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
    cargo bench;
    fi
  - npm i -g npm@6.9.0
  - cd broswer-extension && npm test -- --firefox
