[package]
name = "resume"
version = "0.1.0"
authors = ["Dunja Lalic"]
edition = "2018"
license = "MIT"
default-run = "resume"

[dependencies]
anyhow = "1.0.44"
askama = "0.10.5"
byteorder = "1.4.3"
chrono = {version = "0.4.19", features = ["serde"]}
clap = {version = "2.33.3", features = ["yaml"]}
dirs = "4.0.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_yaml = "0.8.21"

[dev-dependencies]
proptest = "1.0.0"

[[bench]]
name = "color"
harness = false
