[package]
name = "resume"
version = "0.1.0"
authors = ["Dunja Lalic"]
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.56"
askama = "0.11.1"
byteorder = "1.4.3"
chrono = { version = "0.4.19", features = ["serde"] }
clap = { version = "3.1.7", features = ["derive"] }
dirs = "4.0.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"

[dev-dependencies]
proptest = "1.0.0"

[[bench]]
name = "color"
harness = false
