[package]
name = "resume"
version = "0.1.0"
authors = ["Dunja Lalic"]
edition = "2018"
license = "MIT"
default-run = "resume"

[dependencies]
askama = "0.10.2"
byteorder = "1.3"
chrono = {version = "0.4", features = ["serde"]}
clap = {version = "2.33", features = ["yaml"]}
dirs = "3.0"
failure = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"

[dev-dependencies]
proptest = "0.10"
