[package]
name = "resume"
version = "0.1.0"
authors = ["Dunja Lalic"]
edition = "2018"
license = "MIT"
default-run = "resume"

[dependencies]
askama = "0.8.0"
byteorder = "1.3"
chrono = {version = "0.4", features = ["serde"]}
clap = {version = "2.33", features = ["yaml"]}
dirs = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
failure = "0.1"

[dev-dependencies]
proptest = "0.9"
criterion = "0.3"

[[bench]]
name = "color"
harness = false
