[package]
name = "resume"
version = "0.1.0"
authors = ["Dunja Lalic"]
edition = "2018"
license = "MIT"
default-run = "resume"

[dependencies]
askama = "0.9.0"
byteorder = "1.3"
chrono = {version = "0.4", features = ["serde"]}
clap = {version = "2.33", features = ["yaml"]}
dirs = "2.0"
failure = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"

[dev-dependencies]
criterion = "0.3"
proptest = "0.9"

[dev-dependencies.cargo-husky]
version = "1"
features = ["run-cargo-fmt"]

[[bench]]
name = "color"
harness = false
